---
- name: Install Jenkins dependencies and OpenJDK
  ansible.builtin.apt:
    name:
      - openjdk-11-jdk
      - gnupg
    state: present

- name: Add Jenkins GPG key
  ansible.builtin.shell: |
    curl -fsSL https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -

- name: Add Jenkins repository
  ansible.builtin.shell: |
    echo "deb https://pkg.jenkins.io/debian-stable binary/" | sudo tee /etc/apt/sources.list.d/jenkins.list

- name: Update apt cache and install Jenkins
  ansible.builtin.apt:
    update_cache: yes
    name: jenkins
    state: present

- name: Enable and start Jenkins service
  ansible.builtin.systemd:
    name: jenkins
    enabled: yes
    state: started
