networks:
  pihole-net:
    external: true

volumes:
  grafana-storage: {}

services:
  grafana:
    image: grafana/grafana:12.3.0-17718666199
    container_name: grafana
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    networks:
      - pihole-net
    labels:
      - "com.docker.compose.project=grafana"
      - "com.docker.compose.service=grafana"
