apiVersion: 1

contactPoints:
  - orgId: 1
    name: ntfy-alerts
    receivers:
      - uid: ntfy-alerts
        type: webhook
        settings:
          url: http://ntfy:80/alerts
          httpMethod: POST
          httpHeaderName1: Authorization
          title: "{{ template \"default.title\" . }}"
          message: "{{ template \"default.message\" . }}"
        secureSettings:
          httpHeaderValue1: Bearer $__env{NTFY_ALERTS_TOKEN}
        disableResolveMessage: false
