version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/network/authelia"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/network/caddy"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/network/cloudflared"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/network/diun"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/network/grafana"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/network/homarr"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/network/loki"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/network/network-pi-metrics"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/network/ntfy"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/network/pihole"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/network/prometheus"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/network/uptime-kuma"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/network/registry-mirror"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
