
services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesResolvers.local.acme.httpChallenge=true"
      - "--certificatesResolvers.local.acme.httpChallenge.entryPoint=web"
      - "--certificatesResolvers.local.acme.email=your-email@example.com"
      - "--certificatesResolvers.local.acme.storage=/letsencrypt/acme.json"
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik/traefik.yml:/traefik/traefik.yml"
      - "./traefik/acme.json:/letsencrypt/acme.json"
      - "./data/traefik:/traefik/data"
    networks:
      - web

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    volumes:
      - "./data/jenkins:/var/jenkins_home"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=PathPrefix(`/jenkins`)"
      - "traefik.http.routers.jenkins.entrypoints=web"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
    networks:
      - web

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - "./data/prometheus:/prometheus"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=PathPrefix(`/prometheus`)"
      - "traefik.http.routers.prometheus.entrypoints=web"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
    networks:
      - web

networks:
  web:
    driver: bridge
