global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

log:
  level: DEBUG

providers:
  file:
    directory: "/etc/traefik"
    watch: true
  docker:
    watch: true
    endpoint: "unix:///var/run/docker.sock"
    network: traefik
    swarmMode: false
    exposedByDefault: false

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: "websecure"

  websecure:
    address: :443
