---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install common packages
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present

- name: Set up UFW and allow firewall rules
  block:
    - name: Enable UFW
      ansible.builtin.shell: |
        echo "y" | ufw enable
      ignore_errors: yes

    - name: Apply UFW firewall rules
      ansible.builtin.command: "{{ item }}"
      loop: "{{ firewall_rules }}"
