global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: resto-rate-local-rpc
    static_configs:
      - targets: [192.168.1.173:3001]
    metrics_path: /metrics
