networks:
  homelab-net:
    name: homelab-net
    driver: bridge
services:
  caddy:
    build: ./caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    dns:
      - 127.0.0.1
      - 1.1.1.3
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    network_mode: "host"
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:8080"
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    environment:
      - TZ=Europe/Warsaw
      - FTLCONF_webserver_api_password=${PIHOLE_ADMIN_PASS}
      - FTLCONF_dns_listeningMode=all
      - FTLCONF_dns_upstreams=1.1.1.3;1.0.0.3
      - FTLCONF_webserver_port=8080
      - FTLCONF_dhcp_enabled=false
      - FTLCONF_webserver_use_https=true
      - FTLCONF_webserver_https_port=8080
      - VIRTUAL_HOST=pihole.mati-lab.online
      - PROXY_LOCATION=/
      - PROXY_SUBDIR=/
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - NET_BROADCAST
    restart: unless-stopped
    networks:
      - homelab-net
