services:
#  caddy:
#    build: ./caddy
#    container_name: caddy
#    restart: unless-stopped
#    ports:
#      - "80:80"
#      - "443:443"
#      - "443:443/udp"
#    dns:
#      - 1.1.1.1
#      - 1.0.0.1
#    environment:
#      - CF_API_TOKEN=${CF_API_TOKEN}
#    volumes:
#      - ./caddy/conf:/etc/caddy
#      - caddy_data:/data
#      - caddy_config:/config

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    networks:
      macvlan-pihole:
        ipv4_address: 192.168.1.253
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    environment:
      - TZ=Europe/Warsaw
      - FTLCONF_webserver_api_password=${PIHOLE_ADMIN_PASS}
      - FTLCONF_dns_listeningMode=all
      - FTLCONF_dns_upstreams=1.1.1.3;1.0.0.3
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - NET_BROADCAST
    restart: unless-stopped

#volumes:
#  caddy_data:
#  caddy_config:

networks:
  macvlan-pihole:
    name: macvlan-pihole
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
