version: "3.3"

networks:
  treafik:
    external: true

services:
  traefik:
    image: "traefik:v2.8"
    container_name: "traefik"
    networks:
      - treafik
    ports:
      - "80:80"
      - "443:443"
      - "8888:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "$PWD/cert/:/cert/"
      - "$PWD/conf/:/etc/traefik"

  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    networks:
      - treafik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Path(`/whoami`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"
