log:
  level: INFO

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  local:
    acme:
      email: your-email@example.com
      storage: /traefik/acme.json
      httpChallenge:
        entryPoint: web

api:
  dashboard: true
