version: '2.1'

services:
  fe:
    image: novyl/jtl-reporter-fe:v4.4.2
    ports:
      - "2020:80"
    depends_on:
      - db
      - be

  db:
    container_name: jtl-reporter-db
    build:
      context: ./db/
      dockerfile: Dockerfile
    volumes:
      - ./data/jtl_reporter_v4:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    user: "$UID:$GID"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  be:
    image: novyl/jtl-reporter-be:v4.4.3
    ports:
      - "5005:5000"
    environment:
      - DB_HOST=db
      - JWT_TOKEN=at-10b43685-c750-490b-822c-ecbd7bd8d067 # please change this token
      - JWT_TOKEN_LOGIN=at-0e86d61a-8c76-4969-800e-d77a4857776c  # please change this token, the same must be used for listener service

  migration:
    image: novyl/jtl-reporter-be:v4.4.3
    environment:
      - DATABASE_URL=postgres://postgres@db/jtl_report
    command: npm run migrate up
    depends_on:
      db:
        condition: service_healthy

  listener:
    image: novyl/jtl-reporter-listener-service:v2.0.4
    ports:
      - "6000:6000"
    environment:
      - DB_HOST=db
      - JWT_TOKEN=at-6f2363c5-904a-4d3d-b704-339e91d11815 # paste the same token as in be service - JWT_TOKEN_LOGIN

  scheduler:
    image: novyl/jtl-reporter-scheduler:v0.0.2
    environment:
      - DB_HOST=db
