networks:
  pihole-net:
    external: true

services:
  pve-exporter:
    image: prompve/prometheus-pve-exporter:latest
    container_name: pve-exporter
    restart: always
    security_opt: [no-new-privileges:true]
    networks: [pihole-net]
    environment:
      PVE_USER: ${PVE_USER}
      PVE_TOKEN_NAME: ${PVE_TOKEN_NAME}
      PVE_TOKEN_VALUE: ${PVE_TOKEN_VALUE}
      PVE_VERIFY_SSL: "false"
    env_file:
      - .env
    labels:
      - "com.docker.compose.project=pve-exporter"
      - "com.docker.compose.service=pve-exporter"
