pageInfo:
  title: mati-lab.online
  navLinks: []
appConfig:
  theme: one-dark
  layout: auto
  iconSize: small
sections:
  - name: Monitoring
    displayData:
      sortBy: most-used
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items: []
    widgets:
      - type: clock
        options:
          timeZone: Europe/Warsaw
          format: pl-PL
          hideDate: false
        id: 0_1062_clock
