version: '3.8'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    privileged: true
    restart: always
    user: root
    ports:
      - 8888:8080
      - 50000:50000
    volumes:
      - ./jenkins_conf/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
