version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    network_mode: host
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"    # Jenkins UI
      - "50000:50000"  # Agent connections
    volumes:
      - ./jenkins_home:/var/jenkins_home
    environment:
