networks:
  pihole-net:
    external: true

volumes:
  alertmanager-data: {}

services:
  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: alertmanager
    restart: always
    security_opt: [no-new-privileges:true]
    networks: [pihole-net]
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/alertmanager
      - --web.external-url=https://alertmanager.mati-lab.online
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager-data:/alertmanager
    labels:
      - "com.docker.compose.project=alertmanager"
      - "com.docker.compose.service=alertmanager"
