- name: Provision Proxmox Alpine VMs with Layered Configurations
  hosts: proxmox
  gather_facts: false

  vars_files:
    - vault.yml
    - group_vars/ubuntu_default.yml
    - group_vars/{{ vars_file }}

  tasks:
    - name: Clone the VM from the template
      community.general.proxmox_kvm:
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        api_host: "{{ api_host }}"
        validate_certs: "{{ validate_certs }}"
        node: "{{ target_node }}"
        clone: "{{ template }}"
        name: "{{ vm_name }}"
        state: present
        full: true
        sshkeys: "{{ vault_ssh_public_key }}"
        ciuser: "root"
        cipassword: "root"
        agent: 1

    - name: Update hardware configuration for the VM
      community.general.proxmox_kvm:
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        api_host: "{{ api_host }}"
        validate_certs: "{{ validate_certs }}"
        node: "{{ target_node }}"
        name: "{{ vm_name }}"
        memory: "{{ memory }}"
        cores: "{{ cores }}"
        sockets: 1
        scsi:
          storage: "{{ storage }}"
          size: "{{ disk_size }}"
        state: present

    - name: Start the VM
      community.general.proxmox_kvm:
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        api_host: "{{ api_host }}"
        validate_certs: "{{ validate_certs }}"
        node: "{{ target_node }}"
        name: "{{ vm_name }}"
        state: started

    - name: Apply the common role for basic setup
      include_role:
        name: common

    - name: Apply the Docker role if Docker is enabled
      when: docker_enabled
      include_role:
        name: docker

    - name: Apply the Jenkins role if Jenkins-specific config is selected
      when: vars_file == "ubuntu_jenkins.yml"
      include_role:
        name: jenkins
