networks:
  pihole-net:
    external: true

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - ./app/data:/app/data
    networks:
      - pihole-net
    dns:
      - 192.168.1.252
    labels:
      - "com.docker.compose.project=uptime-kuma"
      - "com.docker.compose.service=uptime-kuma"
