networks:
  pihole-net:
    external: true

services:
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - pihole-net
    labels:
      - "com.docker.compose.project=prometheus"
      - "com.docker.compose.service=prometheus"

volumes:
  prometheus-data: {}
