networks:
  pihole-net:
    external: true

services:
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    restart: always
    security_opt: [no-new-privileges:true]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules:/etc/prometheus/rules:ro
      - prometheus-data:/prometheus
    networks:
      - pihole-net
    labels:
      - "com.docker.compose.project=prometheus"
      - "com.docker.compose.service=prometheus"
      - "homepage.group=Observability"
      - "homepage.name=Prometheus"
      - "homepage.icon=prometheus.png"
      - "homepage.href=https://prometheus.mati-lab.online"
      - "homepage.description=Time-series DB + scrape jobs"
      - "homepage.widget.type=prometheus"
      - "homepage.widget.url=http://prometheus:9090"

volumes:
  prometheus-data: {}
